version: '3'
services: 
  admin:
    build:  
     context: ./admin
     args:
      - workdir=/go/src/github.com/javasgl/apkAdmin/admin
    ports:
     - '8888:8000'
    volumes:
      - './admin:/go/src/github.com/javasgl/apkAdmin/admin'
    command: bee run watchall
    links:
      - mysql
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_ROOT_PASSWORD=123456 #mysql root password
    ports:
      - '3306:3306'    #mysql port
    volumes:
      - './mysql/conf:/etc/mysql/conf.d' #mysql custom conf files
      - './mysql/datadir:/var/lib/mysql' #mysql data files
    tty: true 
  phpmyadmin:
    build:
      context: ./phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=123456
    restart: always
    ports:
      - '8080:80'
